name: Run Regression Tests for CPU nightly binaries

on:
  # run every day at 6:15am
  #schedule:
  #  - cron:  '15 6 * * *'
  push:

concurrency:
  group: ci-cpu-${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  regression-cpu-nightly-binaries:
    # creates workflows for OS: ubuntu, macOS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macOS-latest]
        python-version: ["3.8", "3.9", "3.10"]
        binaries: ["pypi", "conda"]
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: recursive
      - name: Setup conda with Python ${{ matrix.python-version }}
        run: |
          if [ "${{ matrix.os }}" == "macOS-latest" ] && [ "${{ matrix.python-version }}" == "3.8" ]; then
            echo "Skipping setup of conda with Python 3.8 on macOS-latest"
          else
            uses: s-weigand/setup-conda@v1
            with:
              update-conda: true
              python-version: ${{ matrix.python-version }}
              conda-channels: anaconda, conda-forge
          fi
      - run: conda --version
      - run: python --version
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Checkout TorchServe
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python ts_scripts/install_dependencies.py --environment=dev
      - name: Validate Torchserve CPU Regression
        run: |
          if [ "${{ matrix.os }}" == "macOS-latest" ] && [ "${{ matrix.python-version }}" == "3.8" ]; then
            echo "Skipping validation for macOS-latest with Python 3.8"
          else
            python test/regression_tests.py --binaries --${{ matrix.binaries }} --nightly
          fi
